reddit/reddit-plugin-adzerk

reddit_adzerk/adzerkpromote.py
This seems like a bug in the requests package.
The exception occurs here:
https://github.com/kennethreitz/requests/blob/master/requests/models.py#L773
because `encoding` is `None`
fixes the "Bassoons" exception
:eyeglasses: @umbrae @kemitche @dwick
=> Handle exception in requests.response.text.

reddit_adzerk/adzerkpromote.py
All of the providers are moving under a single tree for consistency and
cleanliness.
:eyeglasses: @bsimpson63
=> Rename Adzerk API response timer for consistency with other timers.

reddit_adzerk/adzerkpromote.py
This ensures we send proper json for api requests.
:eyeglasses: @kemitche @ajacksified
=> POST_request_promo: use `responsive` to wrap response.

reddit_adzerk/adzerkpromote.py
:eyeglasses: @dwick 
There may be an issue with passing an `int` type to the Adzerk request. This will pass a `str` type, which has proven to work in the case of logged out users via the `loid`.
=> Pass id36 to Adzerk rather than id

reddit_adzerk/adzerkpromote.py
:eyeglasses: @bsimpson63 @spladug 
Old problem recurring as documented in [JIRA ADS-260](https://reddit.atlassian.net/browse/ADS-260).
This change sanitizes all strings to bytestrings prior to sending to the logger. The operation only takes effect on strings containing non-ASCII characters; it is idempotent on strings comprised entirely on ASCII chars.
=> Force bytestring when logging changes

reddit_adzerk/adzerk_api.py, reddit_adzerk/adzerkpromote.py
These are no longer used.  Also they incorrectly were cached
permanently with no consideration for url updates.
=> Remove static click trackers.

reddit_adzerk/public/static/js/adzerk/display.js
Firefox automatically url encodes the hash fragment where as
other browsers don't.  Since we're expecting the entire fragment
to be json we can simply check that the string starts with `{%22`
and decode it.
=> Display ads: Fix firefox fragment encoding issue.

reddit_adzerk/templates/baseadframe.html
From james:
> Can you change your client script to use preview.adzerk.com instead of preview.adzerk.net? I tried to add an SSL cert for preview.adzerk.net but they don't make a cert that will let us do preview.adzerk.net and *.adzerk.com (or any multiple wildcard domains).
=> Fix ssl for preview links

reddit_adzerk/public/static/js/adzerk/display.js
`keywords` is an array and needs to be iterated as such.
before:
after:
=> Fix bug with ads being skipped when they should not be

reddit_adzerk/adzerkreporting.py
Fixes an edge case when back filling data.  If a report is run a
2nd time well after the campaign has already completed then the
start date used would be that of the first run of the report.
Which in this case is usually greater than the end date.
=> Reporting: Ensure proper start date is used

reddit_adzerk/report.py
FRONTPAGE_NAME is now only used for legacy reporting.  Moved it to
the report module.
:eyeglasses: @bsimpson63
=> Fix import error

reddit_adzerk/report.py
:eyeglasses: @kjoconnor 
cc: @dwick 
Per Adzerk, we need to pass a value, otherwise we get a 400 response: `{"message":"Argument cannot be null.\nParameter name: source"}`.
=> Ensure that GroupBy passes a value

reddit_adzerk/adzerkpromote.py
SiteZoneTargeting hardly ever changes, but causes unchanged flights
to be updated unnecessarily/spam the `PromotionLog` because adzerk
also includes `Id`s in the GET results.
=> Stop unnecessarily updating `SiteZoneTargeting`

reddit_adzerk/public/static/js/adzerk/display.js
This can be targeting via [custom targeting](http://help.adzerk.com/hc/en-us/sections/200425869-Custom-Targeting):
`(percentage > 0 and percentage <= 20)`
ticket: https://reddit.atlassian.net/browse/ADS-527
=> Add a custom property to the ad request for the percentage of users

reddit_adzerk/public/static/js/adzerk/adzerk.js
👓 @tsegaran @aoiwelle 
This should hopefully fix the adx passback: http://help.adzerk.com/hc/en-us/articles/203360135-Alternate-Passback-Code-for-Use-With-Iframes
Adzerk expects the top frame to be the one serving the ad via their ados.js.  We serve the ads from iframes (/ads/300x250) so we need to pass the messages back down to ados to handle.  Currently the passback also throws an error because the postMessage handler expects only strings.
I haven't been able to test this because I can't seem to get the passback to fire anymore.
Maybe @averyj can lend a hand with that.
=> Proxy postMessages down to the ad frame

reddit_adzerk/adzerkreporting.py
They're causing the db to error with:
sqlalchemy.exc.OperationalError: (OperationalError) index
row requires 41136 bytes, maximum size is 8191
👓 @zeantsoi @kjoconnor 
ticket: https://reddit.atlassian.net/browse/ADS-573
=> Fix `target_name` for multi-subreddit targeting being too long.

reddit_adzerk/adzerkpromote.py
Since caps have no pacing add the theoretical maximum number of
impressions as the impression goal to prevent things from wildly
overspending.
👓 @zeantsoi @tsegaran 
this was already fished, looks like z hit the merge button by accident though: https://github.com/reddit/reddit-plugin-adzerk/pull/199
=> Add an impression goal to cpm auction campaigns

reddit_adzerk/templates/baseadframe.html
👓 @aoiwelle 
Adzerk made an update to ados.js to fix the adx passback, but the script is cached with a 7 day TTL.  This ensures we have the latest version of ados via a cache busting param tied to r2's short hash.
=> Add cache busting string to ados.js

reddit_adzerk/templates/passback.html
👓 @aoiwelle 
This crazy bit of code looks for the `divName` property in windows above the adx passback.  If it errors it has hit an unfriendly iframe so it fires off `postMessage` events to every frame at that level, which hopefully is the correct frame.
Seemed to work when tested via the js console.  Current code doesn't work so I don't see any harm in trying this.
=> Search for the correct window before firing the passback

reddit_adzerk/adzerkpromote.py
👓 @aoiwelle 
everything is currently coming in as `unknown (number)` because `priorityId` is a string.
https://interana.data.uw2.snooguts.net/s/b389RL
ticket: https://reddit.atlassian.net/browse/ADS-660
=> Fix priority id not being mapped to names

reddit_adzerk/public/static/js/adzerk/display.js
👓 @aoiwelle 
modifying the `properties` object was turning all the values to strings before publishing events.  we only need this for setting them w/ados.
=> Encode properties only for sending them to ados
