reddit/reddit-plugin-adzerk

- reddit_adzerk/adzerkpromote.py
https://github.com/reddit/reddit-public/pull/3513
> Send CORS headers with POST_request_promo response.

- reddit_adzerk/adzerkpromote.py
> Unset CustomTargeting on Flight when not used.

- reddit_adzerk/adzerkpromote.py
:eyeglasses: @dwick 
I still can't get my local instance to spin up, so this is untested. If I'm missing something, please let me know.
> Decorate Adzerk request to enable identification via OAuth

- reddit_adzerk/adzerkpromote.py
Intermittent adzerk issue caused a scare.  This should be fine now.
:eyeglasses: @bsimpson63
> Revert "Temp: stop passing url"

- reddit_adzerk/adzerkpromote.py
:eyeglasses: @zeantsoi @bsimpson63
> Click tracking

- reddit_adzerk/adzerk_utils.py
- reddit_adzerk/adzerkpromote.py
:eyeglasses: @kjoconnor @bsimpson63 @Deimos
> Return None if OS is not present

- reddit_adzerk/adzerkpromote.py
https://github.com/reddit/reddit-public/pull/4042
> Update served status of campaigns

- reddit_adzerk/adzerk_api.py
- reddit_adzerk/location.py
- reddit_adzerk/report.py
> Use SSL on all adzerk requests

- reddit_adzerk/adzerkpromote.py
> Log the adzerk campaign of an orphaned flight

- reddit_adzerk/lib/cache.py
> Fix data not being loaded

- reddit_adzerk/adzerk_api.py
This will make it easier to figure out what's wrong just by looking at the adzerk_q logs.
:eyeglasses: @spladug @dwick
> adzerk_api: Include response text in exception.

- reddit_adzerk/adzerkpromote.py
see https://github.com/reddit/reddit-public/pull/4204
> Track auto refresh requests

- reddit_adzerk/adzerk_api.py
fixed in the package https://github.com/kennethreitz/requests/commit/2bb49ff386deab4e67e199450085720c1521411a (we're still on 0.12.1)
> adzerk_api.py: Fix exception on bad encoding

- reddit_adzerk/__init__.py
- reddit_adzerk/adzerkads.py
- reddit_adzerk/lib/config.py
- reddit_adzerk/public/static/js/adzerk/adzerk.js
- reddit_adzerk/public/static/js/adzerk/companion.js
- reddit_adzerk/public/static/js/adzerk/display.js
- reddit_adzerk/templates/ad300x250.html
- reddit_adzerk/templates/ad300x250companion.html
- reddit_adzerk/templates/adbaseframe.html
previously adzerk was hosting a lot of this code.  i moved it to the plugin to make changes like this easier (ie not involve adzerk).
> Force adzerk to load specific ads based on a query param.

- reddit_adzerk/__init__.py
- reddit_adzerk/adzerkads.py
- reddit_adzerk/lib/config.py
- reddit_adzerk/public/static/js/adzerk/adzerk.js
- reddit_adzerk/public/static/js/adzerk/companion.js
- reddit_adzerk/public/static/js/adzerk/display.js
- reddit_adzerk/templates/ad300x250.html
- reddit_adzerk/templates/ad300x250companion.html
- reddit_adzerk/templates/baseadframe.html
:eyeglasses: @JordanMilne @spladug 
semi unrelated commit restricting the placements feature to sponsors, but i figured might as well deploy them both at once.
> Cache harder

- reddit_adzerk/adzerkpromote.py
> Sponsored headlines: send referrer to adzerk

- reddit_adzerk/adzerkpromote.py
> TEMP: Skip campaigns created on staging w/auction attributes.

- reddit_adzerk/__init__.py
- reddit_adzerk/templates/baseadframe.html
This reverts commit db00057736819edc80f5596ab0b92bafd2265cc0.
:eyeglasses: @zeantsoi we're at 100% so we dont need this anymore
> Revert "TEMP: Move traffic slowly to the DNT domain"

- reddit_adzerk/__init__.py
- reddit_adzerk/adzerkreporting.py
- reddit_adzerk/report.py
- upstart/reddit-consumer-adzerk_reporting_q.conf
- upstart/reddit-job-queue_promo_reports.conf
- Campaign reports are lifetime totals.
- Link reports get a daily breakdown by campaign.
Hourly job: reddit-job-queue_promo_reports.conf
Queue processor: reddit-consumer-adzerk_reporting_q.conf
:eyeglasses: @bsimpson63 @zeantsoi 
puppet stuff coming soon
> Ads reporting: Add jobs to run/process link and campaign reports.

- reddit_adzerk/__init__.py
- reddit_adzerk/adzerkreporting.py
:eyeglasses: @zeantsoi found some bugs and added some more logging to make life a bit easier.
> reporting fixes

- reddit_adzerk/templates/baseadframe.html
> Display ads: Fix js error caused by missing placement

- reddit_adzerk/adzerkads.py
:eyeglasses: @bsimpson63 
This was the change that caused memoize to fail, already been reviewed for the code itself, just wanted to make sure nothing else unforeseen happens.
related: https://github.com/reddit/reddit-public/pull/4478
> Display ads: Use `promote.keywords_from_context` to generate keywords

- reddit_adzerk/adzerkads.py
> Keywords no filtering

- reddit_adzerk/__init__.py
- reddit_adzerk/adzerkpromote.py
- reddit_adzerk/lib/config.py
https://reddit.atlassian.net/browse/ADS-271
> Add support for native

- reddit_adzerk/adzerkpromote.py
> Don't allow ads tagged as nsfw to show up on the frontpage

- reddit_adzerk/public/static/js/adzerk/display.js
> Fix bad truth test

- reddit_adzerk/adzerkreporting.py
> Fix stats namespace collision

- reddit_adzerk/adzerkpromote.py
per https://adzerk.slack.com/?redir=%2Farchives%2Fadzerk-reddit%2Fp1450477132000044
> Send budget caps in dollar amounts

- reddit_adzerk/adzerkreporting.py
:eyeglasses: @bsimpson63, @zeantsoi 
sample log (single process):
```
Dec 28 10:23:58 job-01 adzerk_reporting_q_1: generating report for campaign t8_mi57
Dec 28 10:23:59 job-01 adzerk_reporting_q_1: trigger processing for campaign (t8_mi57/5dc2b42b-2e8c-4909-acae-b2c4bdd6f7dc)
Dec 28 10:23:59 job-01 adzerk_reporting_q_1: processing report for campaign (t8_mi57/5dc2b42b-2e8c-4909-acae-b2c4bdd6f7dc)
Dec 28 10:24:00 job-01 adzerk_reporting_q_1: successfully processed report for campaign (t8_mi57/5dc2b42b-2e8c-4909-acae-b2c4bdd6f7dc)
Dec 28 10:24:00 job-01 adzerk_reporting_q_1: generating report for link t3_3qlfz2
Dec 28 10:24:00 job-01 adzerk_reporting_q_1: trigger processing for link (t3_3qlfz2/0431bedf-517b-4914-9a05-d0ba1256bf26)
Dec 28 10:24:00 job-01 adzerk_reporting_q_1: processing …
```
> Ad reporting sync

- reddit_adzerk/adzerkreporting.py
> Fix exiting before all messages are written to rabbit

- reddit_adzerk/__init__.py
- reddit_adzerk/adzerkpromote.py
- reddit_adzerk/lib/events.py
:eyeglasses: @zeantsoi @Deimos 
ticket: https://reddit.atlassian.net/browse/ADS-256
spec: https://reddit.atlassian.net/wiki/display/DA/Ad+Serving+Events
cc @drunken-economist
> Instrument

- reddit_adzerk/__init__.py
> Fix `events_collector_ad_serving_sample_rate` type specification

- reddit_adzerk/__init__.py
- reddit_adzerk/adzerkpromote.py
- reddit_adzerk/lib/validator.py
This allows clients to not have to worry about the logic around
which keywords (srnames) to send.
> Use site to derive keywords directly if provided

- reddit_adzerk/adzerkreporting.py
Adzerk responds with multiple details records if the price changes.
We need to aggregate on those.
From them:
> If you change the rate of a flight in the middle of the day (or in between start adn end date as it was the case here), we'll show the impressions for the one rate in one line item, and the impressions for the other rate in another.
> Aggregate reporting records by campaign/date

- reddit_adzerk/adzerkreporting.py
> Log correct sleep time

- reddit_adzerk/adzerkpromote.py
looks like i missed a spot :(. i'll make sure existing stuff is updated.
> Update keyword used for the frontpage

- reddit_adzerk/adzerkads.py
- reddit_adzerk/lib/config.py
- reddit_adzerk/public/static/js/adzerk/display.js
https://reddit.atlassian.net/browse/ADS-355
> Pass subreddit to adzerk as custom property

- reddit_adzerk/adzerkpromote.py
recommended by larry at adzerk.
> Tell adzerk to filter out known bots

- reddit_adzerk/adzerkpromote.py
Previously we were updating everything about the campaign,
advertiser, and creative when doing simple actions like pausing a
flight.  This should reduce the cost of updates.
> update_adzerk: Only update flight data when a campaign is provided.

- reddit_adzerk/adzerkpromote.py
re: https://reddit.atlassian.net/browse/ADS-417
:eyeglasses: @tsegaran
> Update all flights when a links `over_18` flag is changed

- reddit_adzerk/adzerkpromote.py
:eyeglasses: @zeantsoi @tsegaran 
related to https://github.com/reddit/reddit-public/pull/5009
> Allow for campaigns to be managed externally.

- reddit_adzerk/adzerkpromote.py
> Fix link updates being skipped improperly

- reddit_adzerk/__init__.py
- reddit_adzerk/adzerkads.py
- reddit_adzerk/templates/passback.html
👓 @tsegaran 
per http://help.adzerk.com/hc/en-us/articles/203360135-Alternate-Passback-Code-for-Use-With-Iframes
config: https://github.com/reddit/reddit-private/pull/1384
> Add AdX passback shim

- reddit_adzerk/__init__.py
> Configure `adx_passback_id` as an `int`

- reddit_adzerk/adzerkpromote.py
👓 @zeantsoi 
related to https://github.com/reddit/reddit-public/pull/5030
> Use `promote.is_external` to test for external promotions

- reddit_adzerk/adzerkpromote.py
👓 @zeantsoi 
```
Apr 20 12:27:13 job-01 adzerk_q_1: Traceback (most recent call last):
Apr 20 12:27:13 job-01 adzerk_q_1:   File "/usr/local/bin/paster", line 9, in <module>
Apr 20 12:27:13 job-01 adzerk_q_1:     load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
Apr 20 12:27:13 job-01 adzerk_q_1:   File "/usr/lib/python2.7/dist-packages/paste/script/command.py", line 104, in run
Apr 20 12:27:13 job-01 adzerk_q_1:     invoke(command, command_name, options, args[1:])
Apr 20 12:27:13 job-01 adzerk_q_1:   File "/usr/lib/python2.7/dist-packages/paste/script/command.py", line 143, in invoke
Apr 20 12:27:13 job-01 adzerk_q_1:     exit_code = runner.run(args)
Apr 20 12:27:13 job-01 adzerk_q_1:   File "/usr/lib/python2.7/dist-packages/paste/script/command.py", line 238, in run …
```
> Fix `KeyError` when `triggered_by` is not sent to the queue

- reddit_adzerk/adzerkpromote.py
- reddit_adzerk/lib/events.py
> Add id to serving events for matching events from the same request

- reddit_adzerk/__init__.py
- reddit_adzerk/adzerkpromote.py
👓 @tsegaran @spladug 
Having trouble reproducing and issue with the bourne roadblock on staging so we need some more info.  Not seeing anything weird in any of the statsd graphs either.  @spladug is volume going to be an issue here?  We can probably revert this after we figure out what's going on.
> Dump request and response body to logs

- reddit_adzerk/adzerkpromote.py
> Add DNT to request log

- reddit_adzerk/lib/validator.py
JIRA Ticket:
https://reddit.atlassian.net/browse/ADS-424
Regex Debugger: 
https://www.debuggex.com/
> handled ad hoc multireddit request_promo bug

- reddit_adzerk/adzerkpromote.py
> Pad daily budget cap by 20%

- reddit_adzerk/adzerkpromote.py
👓 @tsegaran @zeantsoi 
related: https://github.com/reddit/reddit-public/pull/5125
> Dont use daily cap during auto extension period

- reddit_adzerk/adzerkreporting.py
👓 @zeantsoi 
docs: http://help.adzerk.com/hc/en-us/articles/208580316-Click-Bucketing
ticket: https://reddit.atlassian.net/browse/ADS-458
No plans to backfill since I think that will just cause confusion.
> Use unique clicks for click counts

- reddit_adzerk/adzerkpromote.py
> Ad response meta data

- reddit_adzerk/adzerkpromote.py
- reddit_adzerk/lib/events.py
👓 @aoiwelle 
https://reddit.atlassian.net/browse/ADS-529
sample adzerk response:
```
{  
"user":{  
"key":"1ukh"
},
"decisions":{  
"div0":{  
"adId":1694579,
"creativeId":1374113,
"flightId":1599777,
"campaignId":375360,
"clickUrl":"https://engine.a.redditmedia.com/r?e=eyJhdiI6MTIzNTA3LCJhdCI6NCwiYnQiOjAsImNtIjozNzUzNjAsImNoIjo3OTg0LCJjayI6e30sImNyIjoxMzc0MTEzLCJkaSI6IjY3ZDU1Mzc3YzkyNzQ3MTlhMWQ5ZWNhOGNiNjY1MWZiIiwiZG0iOjMsImZjIjoxNjk0NTc5LCJmbCI6MTU5OTc3NywiaXAiOiI4LjguOC44Iiwia3ciOiJzLmZyb250cGFnZSIsIm1rIjoicy5mcm9udHBhZ2UiLCJudyI6NTE0NiwicGMiOjEuNSwiZHAiOjEuMDEsImVjIjoxLjUsInByIjo4NDUzNiwicnQiOjIsInJmIjoiaHR0cHM6Ly9yZWRkaXQuY29tLyIsInN0IjoyNDk1MCwidWsiOiIxdWtoIiwidHMiOjE0NjQyODkxNDU2ODgsImJmIjp0cnVlLCJwbiI6ImRpdjAiLCJ1ciI6Imh0dHA6Ly9jLnRlYWxzazEyLm9yZy9sLzUwOCJ9&s=hpa1MoRP0ZQDKKt86XcyiH …
```
> Add rate_type and clearing_price to ad_response events

- reddit_adzerk/adzerkads.py
👓 @aoiwelle 
reported by mike midden.
ticket: https://reddit.atlassian.net/browse/ADS-535
> Allow adx passback url to be framed

- reddit_adzerk/adzerk_api.py
- reddit_adzerk/adzerkpromote.py
> Exclude flight data when updating campaign objects

- reddit_adzerk/adzerkads.py
- reddit_adzerk/public/static/js/adzerk/display.js
👓 @aoiwelle 
ticket: https://reddit.atlassian.net/browse/ADS-548
> Allow `percentage` property to be manually overriden by sponsors

- reddit_adzerk/public/static/js/adzerk/display.js
👓 @aoiwelle 
previously we were sending either 0 or 1.
> Ensure percentages are from 0-100

- reddit_adzerk/adzerkpromote.py
- reddit_adzerk/lib/events.py
need to add `interana_excluded` functionality to baseplate events before review of this
> Add `impression_id` to `ss.ad_response` event

- reddit_adzerk/adzerkpromote.py
> Set dnt=False for links with moat tracking

- reddit_adzerk/adzerkpromote.py
> Handle socket.error in adzerk_request

- reddit_adzerk/adzerkpromote.py
:eyeglasses: @bsimpson63 
Fingers crossed
> Handle select.error in adzerk_request

- reddit_adzerk/adzerkpromote.py
> All full_url to properties

- reddit_adzerk/lib/events.py
> Fix `TypeError` caused by `matched_keywords=None`

- reddit_adzerk/adzerkpromote.py
I'm updating how these are stored in https://github.com/reddit/reddit-public/pull/5549, which is currently partially deployed.  The datetime changes are not currently compatible with this plugin though. 
👓  @zeantsoi @dwick
> update loid_created usage to be compat with new datetime format

- reddit_adzerk/adzerkpromote.py
👓 @tsegaran 
ticket: https://reddit.atlassian.net/browse/ADS-653
> Stop showing CPC ad after a user clicks on it

- reddit_adzerk/adzerkpromote.py
👓 @aoiwelle 
related: https://github.com/reddit/reddit-public/pull/5658
> Use specific placement names instead of number `div`s

- reddit_adzerk/adzerkpromote.py
- reddit_adzerk/lib/events.py
> Use friendly names for placement types

- reddit_adzerk/adzerkpromote.py
> Fix `KeyError` related to looking up ad type friendly names

- reddit_adzerk/public/static/js/adzerk/display.js
> Remove top ad request call for control groups

- reddit_adzerk/adzerkads.py
- reddit_adzerk/public/static/js/adzerk/display.js
> Set is_banner to True for banners

- reddit_adzerk/__init__.py
- reddit_adzerk/adzerkads.py
- reddit_adzerk/templates/passback.html
👓 @zeantsoi 
ticket: https://reddit.atlassian.net/browse/ADS-699
> Allow multiple passbacks to be applied via a query param

- reddit_adzerk/report.py
> Add feature flag for adzerk reporting 2.0

- reddit_adzerk/adzerkreporting.py
> Sort campaigns and request reports in large groupings

- reddit_adzerk/__init__.py
- reddit_adzerk/adzerkpromote.py
- reddit_adzerk/lib/config.py
- reddit_adzerk/lib/events.py
- reddit_adzerk/public/static/js/adzerk/base64.js
- reddit_adzerk/public/static/js/adzerk/display.js
👓 @aoiwelle @tsegaran 
You guy see anything missing/inconsistent? I've added some of my own notes since this is a big change.
related tickets:
https://reddit.atlassian.net/browse/ADS-665
https://reddit.atlassian.net/browse/ADS-418
ss.ad_request:
```json
{  
"event_ts":1471304663611,
"uuid":"1c780f2a-4c6c-4ddf-b1e8-993cdd61136d",
"payload":{  
"referrer_url":"https://dwick.staging.snooguts.net/",
"domain":"dwick.staging.snooguts.net",
"user_id":31462364,
"is_refresh":false,
"user_agent_parsed":{  
"platform_name":"Mac OS",
"platform_version":"X 10.9.5",
"browser_version":"52.0.2743.116",
"os_name":"Macintosh",
"browser_name":"Chrome"
},
"user_features":{  
"NO_MEANINGFUL_ACTIVITY":true,
"NO_RECENT_LOGIN_90":true,
"NO_ACTIVITY":true,
"NO_RECENT_LOGIN_60":true
},
"request_count_prev_ip":107, …
```
> Ad event audit

- reddit_adzerk/public/static/js/adzerk/display.js
> Fix error caused by empty companions

- reddit_adzerk/public/static/js/adzerk/display.js
👓 @tsegaran or @aoiwelle 
related: https://github.com/reddit/reddit-public/pull/5701
> Prefix adserver ids in event payloads

- reddit_adzerk/__init__.py
- reddit_adzerk/adzerkreporting.py
👓 @tsegaran 
related to https://github.com/reddit/reddit-private/pull/1831
> Access reporting timeout from live_config

- reddit_adzerk/adzerkreporting.py
The issue here is that we were previously looking up every campaign for the links which could potentially include really old ones.  The result was that the start_date of the report would be set so early that the report would take forever / timeout.  we're only interested in current data for these reports since it's a daily breakdown so we should only ask for that.
👓 @tsegaran or @aoiwelle 
Tested this in reddit-shell on my staging w/this: https://gist.github.com/dwick/2db8970032b29db7d81a40e0ebc2cafa
> Request link reports for date ranges of active campaigns only

- reddit_adzerk/adzerkpromote.py
> Use `ads_loading_timeout_ms` when request ads from adzerk

- reddit_adzerk/adzerkreporting.py
👓 @zeantsoi 
same as this issue: https://github.com/reddit/reddit-plugin-adzerk/pull/146 but for the lifetime reports instead of the daily ones.
> Fix campaign reports saving incorrect results when price changes
